### ISSUE TITLE
make_csc gives errors and warnings

### ISSUE THREAD

**Issue by TangWentao-UMN** [bodono/scs-matlab#2]
When I execute "make_scs.m", the example runs always output errors and warnings as follows. 
Is it trying to find the 0th column ...? 
I tried to use such an installed SCS to solve a problem. It failed at initialization with the same warnings and errors. 

>> make_scs
Building with 'Microsoft Visual C++ 2015 Professional (C)'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2015 Professional (C)'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2015 Professional (C)'.
MEX completed successfully.
Example run:
WARN: A->p (column pointers) not strictly increasing, column 0 empty
ERROR: A->p (column pointers) decreasing
invalid linear system input data
ERROR: Validation returned failure
Failure:could not initialize work
WARN: A->p (column pointers) not strictly increasing, column 0 empty
ERROR: A->p (column pointers) decreasing
invalid linear system input data
ERROR: Validation returned failure
Failure:could not initialize work
Warm-starting:
WARN: A->p (column pointers) not strictly increasing, column 0 empty
ERROR: A->p (column pointers) decreasing
invalid linear system input data
ERROR: Validation returned failure
Failure:could not initialize work
SUCCESSFULLY INSTALLED SCS
(If using SCS with CVX, note that SCS only supports CVX v3.0 or later).

**Comment by mathewgardiner** [comment]
To supplement this issue, I have the same problem with MATLAB R2018a. I get the same error when SCS runs the example problems after install (as above), and also when using SCS to solve a problem with CVX v3.0 (the same problem works with the other available solvers).

**Comment by bodono** [comment]
I take it this is on Windows? What version? And is it 64 bit?

**Comment by mathewgardiner** [comment]
Yes, this is on Windows 10, 64 bit.

**Comment by bodono** [comment]
I think I know why this is happening, but I don't have a windows machine or a matlab license to test a fix. Is anyone who is having this issue able to test a patch if I send one to them directly?

**Comment by RockyRock** [comment]
I encounter the same issue on Matlab 2017b with Windows 10, if you have a patch I am happy to try this!

**Comment by bodono** [comment]
Ok thanks, save the below into a file called `win64.patch` in the `scs` main directory, then in that directory run `git apply win64.patch` and see if that fixes it.

```
diff --git a/include/glbopts.h b/include/glbopts.h
index 510bfb8..ad2aa8f 100644
--- a/include/glbopts.h
+++ b/include/glbopts.h
@@ -95,9 +95,9 @@ extern "C" {

 #ifdef DLONG
 #ifdef _WIN64
-/* #include <stdint.h> */
-/* typedef int64_t scs_int; */
-typedef long scs_int;
+#include <stdint.h>
+typedef int64_t scs_int;
+/* typedef long scs_int; */
 #else
 typedef long scs_int;
 #endif
```

**Comment by ahading** [comment]
$ git apply win64.patch
error: corrupt patch at line 6

**Comment by ahading** [comment]
@bodono excuse me ,i try this,but still exist,please help me ,thank you

**Comment by ahading** [comment]
@RockyRock excuse me ,Did you deal with the problem?

**Comment by RockyRock** [comment]
Hi, sorry I was meant to do this before going on holidays!
The patch is not working but you can apply it manually to the file: `scs\include\glbopts.h`
You have to uncomment the lines 98 and 99 from this file and comment the line 100.
I have attached the modified file directly, it works for me with this modification.

[glbopts.h.zip](https://github.com/bodono/scs-matlab/files/3529584/glbopts.h.zip)

**Comment by bodono** [comment]
Great, thanks for confirming @RockyRock , I've just made that change in `scs` and `scs-matlab`, so if you pull the latest version down it will have the fix.

**Comment by ahading** [comment]
@bodono @RockyRock thank you !  Whale Done
