### ISSUE TITLE
Error when running make_scs

### ISSUE THREAD

**Issue by hastinakisa** [bodono/scs-matlab#4]
I get the following error when trying to install scs by running make_scs:

Error using mex
C:\Users\DELL\Documents\MATLAB\scs\linsys\direct\external\amd_order.c not found; check that you are in the correct
current folder, and check the spelling of 'C:\Users\DELL\Documents\MATLAB\scs\linsys\direct\external\amd_order.c'.

Error in compile_direct (line 17)
eval(cmd);

Error in make_scs (line 43)
compile_direct(flags, common_scs);

What is wrong with it? I really appreciate your help.

**Comment by bodono** [comment]
Should be fixed now.
